{
 "title": "Graylog",
 "description": "A Graylog dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(gl_buffer_usage{type=\"input\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Buffer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_buffer_usage{type=\"input\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}  Usage"
    },
    {
     "expr": "gl_buffer_size{type=\"input\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}  Max"
    }
   ]
  },
  {
   "title": "Process Buffer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_buffer_usage{type=\"process\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Usage"
    },
    {
     "expr": "gl_buffer_size{type=\"process\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "Output Buffer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_buffer_usage{type=\"output\", instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}} Usage"
    },
    {
     "expr": "gl_buffer_size{type=\"output\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Messages received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gl_input_throughput{instance=~\"$instance\"} [1m])",
     "legendFormat": "{{instance}} Input"
    },
    {
     "expr": "rate(gl_output_throughput{instance=~\"$instance\"} [1m])",
     "legendFormat": "{{instance}} Output"
    }
   ]
  },
  {
   "title": "Messages appended to disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_journal_append_1_sec_rate{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} append"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Journal utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gl_journal_utilization_ratio", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Journal size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gl_journal_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Usage"
    },
    {
     "expr": "gl_journal_size_limit{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Limit"
    }
   ]
  },
  {
   "title": "Thread counts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Threads"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total{instance=~\"$instance\",job=\"Graylog\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "Input Thoughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gl_input_throughput{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}